### ISSUE TITLE
Just a quick question

### ISSUE THREAD

**Issue by Aareon** [hclivess/Bismuth#104]
Why do you use time.sleep in most of your modules in this repository?

**Comment by hclivess** [comment]
Hello, mainly for two purposes. To decrease load on server and to wait until a lock is released (instant checking without sleep again causes high CPU load.

**Comment by Aareon** [comment]
What server are we referencing? The clients own node?

**Comment by hclivess** [comment]
Yes, like https://github.com/hclivess/Bismuth/blob/master/node.py#L1633
The rest is waiting for locks to release, or pausing the client for a given period of time not to take 100% CPU. This can cause some lag in consensus, but should even out with more nodes connected

**Comment by Aareon** [comment]
I would suggest a rewrite incorporating asyncio. I have no issue partaking in the rewrite as this project truly interests me.

**Comment by hclivess** [comment]
I recommend testing asyncio on miner, it could then be used as a reference code for the rest of the transcription. Studying asyncio now, as I have no previous experience.

**Comment by maccaspacca** [comment]
Would like to have a view of that for optihash too. This is pretty good at moment in respect of scanning nonces but there is improvement to be had in respect of overall process creation etc.
