### ISSUE TITLE
Requesting overall enhancement to remove globals

### ISSUE THREAD

**Issue by Aareon** [hclivess/Bismuth#107]
The use of global variables is generally frowned upon in Python. I will provide references to questions and documentation that support this proposal.

[One Stackoverflow question](https://stackoverflow.com/questions/22796917/what-does-global-variables-are-bad-mean)
[Another Stackoverflow question](https://stackoverflow.com/questions/11462314/python-alternatives-to-global-variables)
[This user article](http://amir.rachum.com/blog/2013/07/09/python-common-newbie-mistakes-part-2/)

Please let me know if you have any questions, explanation, or need some help making this change.

**Comment by hclivess** [comment]
Thanks for feedback, it was generally easier to create globals than to pass variables from function to function. It hopefully will be improved in the future.

**Comment by Aareon** [comment]
I notice a lot of bad practices, after having my own bad practices pointed out to me so many times. Do you perhaps use Discord so we can talk more about these types of things a little easier?

**Comment by hclivess** [comment]
Yes, I have also noticed several bad practices after going though code with what I've learned from @mikeckennedy. Head over to https://cryptobismuth.herokuapp.com/ and perhaps #dev channel

**Comment by mikeckennedy** [comment]
Hi @hclivess Could you give me some examples of bad practices you think I'm presenting? I'm guessing this is from one of my courses (code should be on GitHub). Not trying to be defensive. I'm genuinely curious what you're referring to.

**Comment by hclivess** [comment]
@mikeckennedy Hello Mike, sorry for the misunderstanding, I meant you helped me to fix some of my bad practices, for example in how strings are handled.

**Comment by mikeckennedy** [comment]
Hey @hclivess yes I must have misunderstood. So glad to help polish the code concepts.
