### ISSUE TITLE
simple json swap for picklemagic at the nearest hardfork

### ISSUE THREAD

**Issue by hclivess** [hclivess/Bismuth#110]
```
import json, picklemagic

input = ""foáýřžřžýčřčšřžčšýžřčýááýžíéáýáýíéííéíéáíéo\bar"

x = json.dumps(input)
print (x)
y = json.loads(x)
print (y)


z = picklemagic.safe_dumps(input)
print (z)
a = picklemagic.safe_loads(z)
print (a)
```

**Comment by hclivess** [comment]
"\"\\\"fo\u00e1\u00fd\u0159\u017e\u0159\u017e\u00fd\u010d\u0159\u010d\u0161\u0159\u017e\u010d\u0161\u00fd\u017e\u0159\u010d\u00fd\u00e1\u00e1\u00fd\u017e\u00ed\u00e9\u00e1\u00fd\u00e1\u00fd\u00ed\u00e9\u00ed\u00ed\u00e9\u00ed\u00e9\u00e1\u00ed\u00e9o\\bar\""
"\"foáýřžřžýčřčšřžčšýžřčýááýžíéáýáýíéííéíéáíéo\bar"
b'\x80\x04\x95_\x00\x00\x00\x00\x00\x00\x00\x8c["\\"fo\xc3\xa1\xc3\xbd\xc5\x99\xc5\xbe\xc5\x99\xc5\xbe\xc3\xbd\xc4\x8d\xc5\x99\xc4\x8d\xc5\xa1\xc5\x99\xc5\xbe\xc4\x8d\xc5\xa1\xc3\xbd\xc5\xbe\xc5\x99\xc4\x8d\xc3\xbd\xc3\xa1\xc3\xa1\xc3\xbd\xc5\xbe\xc3\xad\xc3\xa9\xc3\xa1\xc3\xbd\xc3\xa1\xc3\xbd\xc3\xad\xc3\xa9\xc3\xad\xc3\xad\xc3\xa9\xc3\xad\xc3\xa9\xc3\xa1\xc3\xad\xc3\xa9o\\bar"\x94.'
"\"foáýřžřžýčřčšřžčšýžřčýááýžíéáýáýíéííéíéáíéo\bar"

**Comment by hclivess** [comment]
json: 253 symbols
picklemagic: 385 symbols

**Comment by Aareon** [comment]
This should be in a project, not an issue

**Comment by hclivess** [comment]
Thanks, I used issues for everything, didn't notice the tab

**Comment by hclivess** [comment]
basically implemented
