### ISSUE TITLE
Repo uneccessarily big

### ISSUE THREAD

**Issue by trvrm** [hclivess/Bismuth#113]
```
du -h .git/objects/pack/
461M    .git/objects/pack/
```

`git verify-pack` and `git rev-list --objects --all` indicate that this is due to various .exe and .db files that have been added and then deleted to the repository, but are still in its history.

This may not be considered a bug, but it seems weird to have to clone nearly half a GB to get 2MB worth of code.

**Comment by trvrm** [comment]
I'm not an expert in git operations, but this might help:

https://docs.acquia.com/article/removing-large-files-git-without-losing-history

**Comment by hclivess** [comment]
thanks

**Comment by hclivess** [comment]
I don't want to break things here however, so I think the proper way will be to rename the repo to "old" and start a fresh one

**Comment by hclivess** [comment]
New repo in place
