### ISSUE TITLE
Make a sum table

### ISSUE THREAD

**Issue by hclivess** [hclivess/Bismuth#125]
For balance verification and fast database operations, make an extra table in the database where balances will be kept and updated, operations will no longer recalculate from all transactions with every step, but only add to the total sum or subtract from it accordingly. This should enable scaling up to millions of users.

**Comment by SaerAlmukhlfi** [comment]
What type of database used ?
I think databases is a bad option with blockchain technology .

**Comment by hclivess** [comment]
as a reference for sqlite main databases

**Comment by hclivess** [comment]
May now be outdated since we use proper database typing

**Comment by hclivess** [comment]
outdated
