### ISSUE TITLE
Mined blocks, but balance is zero

### ISSUE THREAD

**Issue by overwatch37** [hclivess/Bismuth#129]
Relatively new to mining BIS, but not to mining. Using the application, I have 5 mining transactions from my wallet to my wallet, stating I successfully mined. But my balance, even hours later, still shows zero. Does it take longer to verify the transactions or did I do something wrong?

**Comment by SylvainDeaure** [comment]
Hi,
Did you try the online query tool at http://bismuth.online/ledgerquery ?
Mined blocks appears usually very fast, and balance updates with the mining transaction.

**Comment by overwatch37** [comment]
I checked there, and it shows nothing with my address. Here is what the GUI is showing me.
![capture](https://user-images.githubusercontent.com/32803193/31584500-b0445cc8-b17d-11e7-8646-aa3747c05708.PNG)

**Comment by SylvainDeaure** [comment]
Well,
I never experienced that. But if the online tool doesn't show anything for your address, then it's empty,
and what you're seing in the GUI is a bug from reading the local database, not the blockchain.

**Comment by overwatch37** [comment]
Okay, so the transaction log showing five blocks, from my address to my address, is a bug? Got it. 

That's disappointing.

**Comment by SylvainDeaure** [comment]
I'm not part of the core team, they may have more experience on this, but it's rather frequent, for every miner, to have some blocks rolled back (for instance you found a block that was already found half a sec before by another one).
There are also some brief periods where the difficulty is quite low and the network goes crazy for a time before syncing again. If you mine during one of those and went out of sync, this may happen.

Were you mining with a huge hash power? Finding 5 blocks solo is not an easy task!

**Comment by overwatch37** [comment]
No, not a huge hash power. Just a gaming laptop. Trying out solo mining
different coins to see where I should put my focus. I'd like to build a
mining rig and do not want to waste time with anything ASIC mineable or
anything I need 20 GPUs for.

I just figured I got super lucky when those 5 blocks appeared in about 2
minutes of each other.

Seriously though, thank you for the assistance. At least now I know. I have
followed Bismuth for a while, and the only drawback thusfar has been the
lack of information or documentation about the miner.

**Comment by SylvainDeaure** [comment]
You're welcome.

Considering your hash power, either it's a glitch during an out of sync period, or you very very very ... very lucky. I think it's not possible to solo mine BIS anymore, not speaking of a single PC.
One reward may happen once in a while, 5 in a row is just stellar craziness :)

**Comment by hclivess** [comment]
Hi, thanks for clearing this up to the user. We are actively working on a solution, which is currently being tested in the testnet.
