### ISSUE TITLE
Wasted resources

### ISSUE THREAD

**Issue by SylvainDeaure** [hclivess/Bismuth#135]
https://github.com/hclivess/Bismuth/blob/280c6def9cf2d39c9a482a6d6b02c3741ce93e5c/node.py#L1078

On digest_block, we do an intensive task (check transaction list) before simpler tests (block height, diff).
Reversing the order would reject invalid blocks sooner and spare all this bdd readings.

Cheap tests first, then only the costly ones.

**Comment by hclivess** [comment]
You are right, the original design was from simple to complicated, digest needs to be split into individual tasks anyway, this is planned indefinitely
