### ISSUE TITLE
Masternodes performance design

### ISSUE THREAD

**Issue by hclivess** [hclivess/Bismuth#149]
Make index of masternodes every 100 to 1000 blocks based on both balance and spending. Keep that index in a separated table/database. Make payouts every 100 to 1000 blocks of a percentage of the mined coins. Subtract that percentage from the miners. Make a merry-go-round model where nodes take turns in getting rewards.

**Comment by hclivess** [comment]
Index will be based on initial node registration and checking spent coins. Participation in block signing is possible, even though delegation to addresses where collateral is not located. Demo:

OpenField: masternode:register:delegates:x,y,z

Block signing will be between registered and validated (unspent collateral) nodes, possibly taking turns based on registration timestamps.

**Comment by hclivess** [comment]
- Masternodes will take turns in submitting blocks (10% of blocks?), the timeout will be calculated based on the registered masternodes for a given masternode segment interval
Example : 100 registered masternodes for 10000 blocks -> total of 1000 blocks (10%) is allowed to be staked, there are 100 nodes, 1000/100 = 10 (each node could possibly mine 10 blocks, to enforce this, the interval must be 10000 / 10 minutes (1 block per minute) so the timeout is 1000 minutes per node in this example.
- Should this impact mining difficulty?

**Comment by hclivess** [comment]
To avoid double checking for balance, it will be allocated using a normal transaction to a predetermined delegate account, with information in the openfield (who is the delegates account, time in multiplications of intervals?). The delegate integrated in every node will go though received transactions every x thousand blocks, processing releases just like zircodice processes payouts. It will not process transactions instantly to prevent accidental double spending. It will select distinct openfields only on return of balance (and distinct txids of vested funds)

**Comment by hclivess** [comment]
Additional voting based on individual node experience with other masternode's bandwith

**Comment by hclivess** [comment]
instead of delegation fund lock, we could just check balance on block-10000 and use that to determine voting, delegation and PoS. much simpler and easier to implement

**Comment by hclivess** [comment]
it would be much easier to have some kind of coin age calculation instead of delegation script with funds lock

**Comment by EggPool** [comment]
If funds are not locked, then coin age may not be enough, since one could move funds just for some time and get them back. Some (moving or not) average on a past period could do, so everyone has a stable reference for a while (rather than instant values that generate instability). This way, collateral for every MN is fixed for an entire PoS round and can't be manipulated by temporary moving funds.

**Comment by hclivess** [comment]
Or we can have just a simple snapshot for a single block in a block range

**Comment by hclivess** [comment]
now applies to offline staking, design complete
