### ISSUE TITLE
Unneccessary DB reallocation

### ISSUE THREAD

**Issue by EggPool** [hclivess/Bismuth#153]
https://github.com/hclivess/Bismuth/blob/e0d3e3af0ee9af27dfc69047305978c56e6d7dad/node.py#L1674

Is there a good reason those DB handles are redefined at each iteration of the loop, instead of once, just above?

Beware, rework of the "finally" step needed if moved.

(I can mod and test if you want me to)

**Comment by hclivess** [comment]
Hi, these are defined in every thread, formerly it was not allowed to share databases across threads. It can be done using something like this ```sqlite.connect(":memory:", check_same_thread=False)```

**Comment by EggPool** [comment]
Did some tests btw, not so simple. Will have to dig deeper, there's an hidden issue there.

**Comment by hclivess** [comment]
Has been upgraded by @EggPool for mempool, will be done for ledger too when architecture is more objectified
