### ISSUE TITLE
Is  this   a  bug?

### ISSUE THREAD

**Issue by flyfire100** [hclivess/Bismuth#154]
![image](https://user-images.githubusercontent.com/28288582/33437466-0004a67c-d623-11e7-9fd4-ffbfc5bb293f.png)
![image](https://user-images.githubusercontent.com/28288582/33437518-2bd6695c-d623-11e7-909e-5536e02f1335.png)
i think  the  wright  code is
```
def log(logFile, level=str("INFO")):
    if isinstance(level, str):
        level = getattr(logging, level.upper())
    else:
        raise TypeError("level must be a string equal to \"INFO\", \"DEBUG\", or \"WARNING\"")
```
my python is python2.7.5

**Comment by EggPool** [comment]
Hi,
I'm not sure if Bismuth is Python2 compatible.
Please use 3.5 or 3.6

**Comment by hclivess** [comment]
Hi, definitely not 2.x compatible anymore

**Comment by flyfire100** [comment]
OK, I  will  change  my  Python2.x  to  Python3.5
