### ISSUE TITLE
Find dead ends which cause the application to go idle if using ping commands

### ISSUE THREAD

**Issue by hclivess** [hclivess/Bismuth#157]
Probablz related to the missing continuation of communication between an incoming and outgoing connection of two nodes, on some occassions, communication stalls and only pings go though. Without pings, communication terminates instead and a new one is created.

Maybe if we do a "sendsync" command instead of ping, that could also work.

May be caused by something different too.

**Comment by hclivess** [comment]
Tagging @EggPool to join with his ideas about the issue

**Comment by EggPool** [comment]
sendsync I would handle with care, as it induces work and sleep() from the node getting it.

I would first test further on the "blocking" version I made of connections.py.
Got no issue so far (that's several days, a week now) with my dev node.
This version is the same on win and linux and much simpler.

Then, maybe just not send the ping, but keep the "*" data from connections.py as valid but doing nothing.
And keep the "ping" command, when received, valid and doing nothing as well, to avoid breaking connection to nodes that may still send it.

**Comment by hclivess** [comment]
It appears that my assumption about logical errors might have been mistaken. Some nodes keep stable connection over hours on end while other disconnect. Still there are some idling issues even without ping on a low-quality wifi connection. We will see how this will develop with protobuff.
