### ISSUE TITLE
Attempt conversion to tornado

### ISSUE THREAD

**Issue by hclivess** [hclivess/Bismuth#167]

**Comment by hclivess** [comment]
Especially low quality connections still have issues with large blocks, current sockets implementation might now be perfect

**Comment by hclivess** [comment]
http://www.tornadoweb.org/en/stable/httpserver.html

**Comment by HarryR** [comment]
gevent is much easier and straightforward to use.

**Comment by hclivess** [comment]
I'm having issues with their documentation, could only find one specific example

**Comment by HarryR** [comment]
https://gist.github.com/viksit/b6733fe1afdf5bb84a40 is a good example for an async HTTP server using Flask

https://github.com/HarryR/torsody/blob/f148c61c800dcb060dacd04a5914059c02db3760/app/backend.py is an example of a backend queue API processor for gevent:

```

from gevent.queue import JoinableQueue
from gevent.event import AsyncResult

API_QUEUE = JoinableQueue()

class Api(object):
    @staticmethod
    def call(*args, **kwargs):
        result = AsyncResult()
        API_QUEUE.put([result, args, kwargs])
        return result.get()

    def __init__(self):
        self.running = False

    def dispatch(self, args, kwargs):
        if len(args) < 1:
            raise RuntimeError("Args Required")
        funcname = 'api_' + str(args[0])
        args = args[1:]
        if not hasattr(self, funcname):
            raise RuntimeError('Unknwon Function')
        method = getattr(self, funcname)
        return method(*args, **kwargs)

    def api_ping(self):
        return "pong"

    def run(self):
        self.running = True
        while self.running:
            result, args, kwargs = API_QUEUE.get()
            try:
                try:
                    result.set(self.dispatch(args, kwargs))
                except:
                    e = sys.exc_info()[0]
                    traceback.print_exc()
                    result.set_exception(e)
            finally:
                API_QUEUE.task_done()

    def stop(self):
        self.running = False
        API_QUEUE.join()
```

Then you can call it like:

```
api_listener = Api()
gevent.spawn(api_listener.run)

# ... in another thread
Api.call('ping')
```

http://blog.pythonisito.com/2012/08/building-tcp-servers-with-gevent.html

http://sdiehl.github.io/gevent-tutorial/

**Comment by HarryR** [comment]
I only mention gevent because it's easier to port normal socket code to it when you `monkey_patch` stuff, e.g. it acts exactly like threads, but can scale more, without rewriting as much stuff as is necessary with Tornado.

**Comment by hclivess** [comment]
Thanks for the feedback, looks like we will be experimenting with Google Protocol Buffer
