### ISSUE TITLE
Covert all remaining parts of the system from float to decimal

### ISSUE THREAD

**Issue by hclivess** [hclivess/Bismuth#183]

**Comment by Aareon** [comment]
Related, SQLAlchemy directly supports this in an a Pythonic and utilitarian manner.
```py
from sqlalchemy import Column, Text, Numeric
class Table:
    __tablename__ = “test_table”

    address = Column(Text, primary_key=True)
    amount = Column(Numeric(scale=8))
```
http://sqlalchemy-html.readthedocs.io/en/rel_1_0_6/core/type_basics.html

**Comment by Aareon** [comment]
This isn’t a float, it’s a decimal like you were suggesting.

**Comment by hclivess** [comment]
Currently we are using something called NUMERIC in SQL, but I am not sure if it's the same or different column type

**Comment by EggPool** [comment]
The critical things are, imho:
- no added latency
- same results as the current code (can't rely on everyone updating, or updating at the same time)
- same result depending on the platform/os (linux, amd, x86 or amd)

So, in order to think of sqlalchemy as a candidate, I'd like to have some basic test/benchmarking code that shows it's impact on speed and ram is negligible, and that we can run on various systems to check for consistency with well chosen edge cases.
Would be easier to do once at least some of the sql part is ported as a module/class.

**Comment by Aareon** [comment]
@EggPool you may not have seen it, but I did post a gist a little bit ago with an example of one of our tables in SQLAlchemy. As a reference, many production companies including Discord use SQLAlchemy in their various products. It’s safe, verbose, Pythonic, and easy to learn. It’s overall much better than having random SQL queries scattered about a codebase in my opinion.

**Comment by Aareon** [comment]
Keep in mind, any abstraction is going to cause overhead, but I think a minor performance trade-off is something we can take for a more modular and maintainable codebase.

**Comment by Aareon** [comment]
Any degradation in performance we might see will soon be returned back after the rest of the code is cleaned up. There are a ton of improvements that need to be made, dependencies that need removed until after a feature is completed (namely `PyQRCode`), etc. I remain objective when I say that adding SQLAlchemy to our toolkit would be only beneficial to future development and maintenance.

**Comment by EggPool** [comment]
I saw the example.
Of course there would be a small cost in perfs. That would be ok if the cost is small.
But that cost has to be measured beforehand in the context of our real world app.
Same thing for checking that the results will be the same as now and same depending on the OS.
Other things may also be relevant: how does sqlalchemy handle multithread context, do we still have access to low level settings needed to optimize sqlite access...
That's why I was recommending a benchmark/test. That would be a real "proof" it's usable in our case.
We will not just add a lib because "production companies use it" and it's pythonic (I'm pushing, and speaking for myself, I'm not a core Bis dev).

There are many many things to improve. I doubt being pythonic is the #1 priority right now. 
All things will come in time.
Bismuth is a living codebase, with an history and several active devs knowing the code by heart, and working on fixes and new features first instead of being pythonic and respecting PEP, Ok.

Just be patient. I'm listening and willing to improve.
But that will take time, we wont refactor over the week.

**Comment by hclivess** [comment]
I do not hold much respect towards PEP, especially 8 and I think added overhead and dependency really needs to be proven reasonable to be justified, can I see the gist?

**Comment by hclivess** [comment]
back to topic: fee system should be converted in node asap (fee calc function), because float division is otherwise inconsistent and in a worst case scenario could result in a split

**Comment by Aareon** [comment]
@hclivess is there any way you can `grep` for all the modules that use `float` that need to be converted to decimal? Python does have `decimal` in the standard library.

I ask if you can do this because I’m on mobile at the moment.

**Comment by hclivess** [comment]
I can do that with PyCharm, not sure about grep
But the main issue is the float division, which returns different numbers on some occassions, and that particularly is a problem in emptying a wallet with a message included, because fee is calculated based on openfiled/x

**Comment by hclivess** [comment]
I might be wrong here, need to do more testing, but for now fee calculation seems to return the same number, but I know it was an issue in the wallet where changing to decimals helped

**Comment by hclivess** [comment]
`
    time.sleep(float(pause_conf))
        time.sleep(float(pause_conf))
    fee = '%.8f' % float(0.01 + (float(len(openfield)) / 100000))  # 0.01 dust
        fee = '%.8f' % (float(fee) + 10)
        fee = '%.8f' % (float(fee) + 1)
    return float((percent * whole) / 100)
                credit = 0 if credit is None else float('%.8f' % credit)
                debit = 0 if debit is None else float('%.8f' % debit)
                fees = 0 if fees is None else float('%.8f' % fees)
                rewards = 0 if rewards is None else float('%.8f' % rewards)
                end_balance = float('%.8f' % (float(credit) - float(debit) - float(fees) + float(rewards)))
                    hyp.execute("INSERT INTO transactions VALUES (?,?,?,?,?,?,?,?,?,?,?,?)", (db_block_height - depth - 1, timestamp, "Hyperblock", x, float(end_balance), "0", "0", "0", "0", "0",
    return (float('%.13f' % difficulty), float('%.13f' % difficulty2)) #need to keep float here for database inserts support
                        mempool_timestamp = '%.2f' % float(transaction[0])
                        mempool_amount = '%.8f' % float(transaction[3])
                        if float(mempool_amount) < 0:
                        if float(mempool_timestamp) > time.time() + 30:  # dont accept future txs
                        if float(mempool_timestamp) < time.time() - 82800:  # dont accept old txs, mempool needs to be harsher than ledger
                                    debit_tx = float(x[0])
                                    debit_mempool = debit_mempool + debit_tx + float(fee)
                            credit_ledger = 0 if credit_ledger is None else float('%.8f' % credit_ledger)
                            credit = float(credit_ledger)
                            debit_ledger = 0 if debit_ledger is None else float('%.8f' % debit_ledger)
                            debit = float(debit_ledger) + float(debit_mempool)
                            fees = 0 if fees is None else float('%.8f' % fees)
                            rewards = 0 if rewards is None else float('%.8f' % rewards)
                            balance = float('%.8f' % (float(credit) - float(debit) - float(fees) + float(rewards) - float(mempool_amount)))
                            balance_pre = float('%.8f' % (float(credit_ledger) - float(debit_ledger) - float(fees) + float(rewards)))
                            if float(mempool_timestamp) > float(time_now) + 30:
                                app_log.info("Mempool: Future transaction not allowed, timestamp {} minutes in the future".format((float(mempool_timestamp) - float(time_now)) / 60))
                            elif float(time_now) - 86400 > float(mempool_timestamp):
                            elif float(mempool_amount) > float(balance_pre):
                            elif (float(balance)) - (float(fee)) < 0:
            db_timestamp = '%.2f' % float(row[1])
            db_transaction = (str(db_timestamp), str(db_address), str(db_recipient), '%.8f' % float(db_amount), str(db_keep), str(db_openfield))
        last_block_ago = float(result[1])
                db_timestamp_last = float(result[0][2])
                    received_timestamp = '%.2f' % float(transaction[0])
                    received_amount = '%.8f' % float(transaction[3])
                    if float(received_amount) < 0:
                    if float(time_now) + 30 < float(received_timestamp):
                        error_msg = "Future transaction not allowed, timestamp {} minutes in the future".format((float(received_timestamp) - float(time_now)) / 60)
                    if float(db_timestamp_last) - 86400 > float(received_timestamp):
                if float(block_timestamp) <= float(db_timestamp_last):
                        db_timestamp = '%.2f' % float(transaction[0])
                        db_amount = '%.8f' % float(transaction[3])
                                block_debit_address = float(block_debit_address) + float(x[3])
                                    block_fees_address = float(block_fees_address) + float(fee_calculate(db_openfield)) #exclude the mining tx from fees
                        credit_ledger = 0 if credit_ledger is None else float('%.8f' % credit_ledger)
                        credit = float(credit_ledger)
                        debit_ledger = 0 if debit_ledger is None else float('%.8f' % debit_ledger)
                        debit = float(debit_ledger) + float(block_debit_address)
                        fees = 0 if fees is None else float('%.8f' % fees)
                        rewards = 0 if rewards is None else float('%.8f' % rewards)
                        balance_pre = float('%.8f' % (float(credit_ledger) - float(debit_ledger) - float(fees) + float(rewards)))  # without projection
                        balance = float('%.8f' % (float(credit) - float(debit) - float(fees) + float(rewards)))
                        fees_block.append(float(fee))
                                mining_reward = 15 - (float(block_height_new) / float(1000000))  # one zero less
                            reward = '%.8f' % float(mining_reward + sum(fees_block[:-1]))
                        if float(balance_pre) < float(db_amount):
                        elif float(balance) - float(block_fees_address) < 0: #exclude fee check for the mining/header tx
                        time.sleep(float(pause_conf))
                        time.sleep(float(pause_conf))
                        last_block_ago = float(c.fetchone()[0])
                        time.sleep(float(pause_conf))
                                debit_tx = float(x[0])
                                debit_mempool = debit_mempool + debit_tx + float(fee)
                        credit_ledger = 0 if credit_ledger is None else float('%.8f' % credit_ledger)
                        credit = float(credit_ledger)
                        fees = 0 if fees is None else float('%.8f' % fees)
                        rewards = 0 if rewards is None else float('%.8f' % rewards)
                        debit_ledger = 0 if debit_ledger is None else float('%.8f' % debit_ledger)
                        debit = float(debit_ledger) + float(debit_mempool)
                        balance = float('%.8f' % (float(credit) - float(debit) - float(fees) + float(rewards)))
... f...
... f...
                    last_block_ago = float(c.fetchone()[0])
`

**Comment by hclivess** [comment]
Important note: All numbers must be converted from string to decimal, never from float to decimal

**Comment by Aareon** [comment]
Makes perfect sense. I’ll keep that in mind.

**Comment by hclivess** [comment]
beware: decimal may still return scientific notation unless %.xxf is used

**Comment by hclivess** [comment]
done
