### ISSUE TITLE
Take care of transactions in rolled back blocks

### ISSUE THREAD

**Issue by EggPool** [hclivess/Bismuth#185]
When a block gets rolled back, it can embed transactions that disappear from the ledger.
Atm, there is no mechanism to re-issue these transactions, the sender has to take care of checking and re-issuing if needed.

Two options, discussed on the discord:
A/ bobby_jones proposes that the tx are not deleted straight away when they arrive in the ledger, but only when they are buried deep enough.
B/ I suggest that when a node rolls back a block with embedded tx, he pastes these tx again in its own mempool.

A) Could lead to a higher network usage, since a bigger mempool would have to be synced.
It also relies on the miners playing the game, and taking the risk of a block being rejected for cause of a duplicate tx.
B) should be good enough, since each node thus guarantee the validity of what it has in its ledger and mempool. It's just a localized operation. Hence a rolled back transaction will be synced again on the net until it reaches a miner mempool.

**Comment by EggPool** [comment]
Related: 
Some kind of unique transaction ID would be great.
Maybe something like blockNumber-tx_signature?

**Comment by hclivess** [comment]
Signature is a unique identifier, I like the idea of putting rolled back transactions back to the mempool. probably will implement that, currently there is backup.db, but that is not really used for anything

**Comment by hclivess** [comment]
Implemented, basic testing passed, may reopen when issues appear
