### ISSUE TITLE
Errors and issues when trying to unlock wallet

### ISSUE THREAD

**Issue by masterminerking** [hclivess/Bismuth#193]
I have 2 issues with regards to unlocking my wallet and I don't know if they are related or not. This is with a Node on one machine and a Wallet on a different machine.

Firstly when I try to Unlock my wallet and enter my password it does nothing then after about 30 secs then I get a message saying that the Wallet has lost connection with the Node then the Wallet closes. There is no message shown in the Terminal window.

Secondly if I purposely type an incorrect password the Wallet closes and I notice these errors in the Terminal window:
Exception in Tkinter callback
Traceback (most recent call last):
 File "/usr/lib/python3.5/tkinter/__init__.py", line 1562, in __call__
   return self.func(*args)
 File "wallet.py", line 466, in <lambda>
   enter = Button(top4, text="Unlock", command=lambda: decrypt_fn(top4))
 File "wallet.py", line 493, in decrypt_fn
   return key
NameError: name 'key' is not defined

**Comment by hclivess** [comment]
I will test this, thanks for reporting. Did you try to connect to one of the nodes from peerlist instead? Unlocking of wallet happens locally, but there could have been some changes that broke the code.

**Comment by masterminerking** [comment]
Thanks. No I did not try to connect to one of the nodes from the peerlist. If you let me know what I need to do I can certainly try it.

**Comment by masterminerking** [comment]
As an experiment I imported my keys onto the same machine as my wallet and I could then unlock my wallet fine. However for security I would like my wallet on a different machine so am intrigued if your test worked or not?

**Comment by hclivess** [comment]
You have to change light_ip in config.txt
I am testing now

**Comment by hclivess** [comment]
OK, test passed when I tested on the acc pool address 66.70.181.150
Are you sure the issue is not related to your machine configuration?

**Comment by masterminerking** [comment]
It must be my setup if its working for you but I don't see how, especially when the wallet is connecting to the Node fine and updating. I set the "light_ip" (wallet side) and allow (node side) in the two config.txt. I will have another try. Thanks for getting back to me, its much appreciated.

**Comment by hclivess** [comment]
I will leave this open until we figure out what is going on, could be an issue for more users

**Comment by hclivess** [comment]
Do you have some custom configuration in config.txt or config_custom.txt? Can you try removing those files only with config.txt from the installation/github?

**Comment by masterminerking** [comment]
I have just tried all of this again with the new 4.2.3.1 wallet and node and I'm having exactly the same issue and get a connection to node aborted pop up message. This is with a completely clean install and the config files only being changed with the "light_ip" (wallet side) and allow (node side) in the two config.txt. I am again receiving blocks and my wallet is up to date and everything seems perfectly normal.

It does seem to take ages until the connection to node aborted pop up message pops up so I'm wondering if there is some sort of timeout issue.

**Comment by masterminerking** [comment]
In addition to my comment above I think the problem is a Raspberry Pi 3. I have tried again with both Node and Wallet on the Pi and get the same issue. This works fine with a normal PC. Not quite sure why it wont work properly with a Pi but it just doesn't seem to.

**Comment by hclivess** [comment]
Hi, what is your OS Locale?

Wallet handling has been upgraded

**Comment by masterminerking** [comment]
My locale is GB and the character set is UTF-8.

**Comment by masterminerking** [comment]
I have just tried this with the new updated wallet (4.2.4.8) and it now seems to be working on the Pi 3. It seems to take ages to unlock, about 45 seconds, but it does seem to be working now and not losing connection and closing as previously. I had to install additional dependencies on top of those in the requirements.txt to get it working but it now certainly seems to unlock and lock fine.

**Comment by hclivess** [comment]
Yeah, the wallet encryption is a bit demanding on the CPU, but should be futureproof
