### ISSUE TITLE
Proof of stake implementation

### ISSUE THREAD

**Issue by hclivess** [hclivess/Bismuth#20]
Proof of stake would be the same mechanism as mining is currently. With each sent transaction, clients would claim a reward based on the amount of coins already owned.

**Comment by crazysoldier** [comment]
Please explain this more,
how is a proof of stake block been generated?

**Comment by hclivess** [comment]
Hi, this is just a proposal without any specific concept

**Comment by titanomachy** [comment]
The update delegated proof of stake text from Dan is here: https://steemit.com/dpos/@dantheman/dpos-consensus-algorithm-this-missing-white-paper

**Comment by hclivess** [comment]
All forms of POS bring unnecessary complications. For now we will focus on masternodes and hashwork concept.
