### ISSUE TITLE
[Wallet] Add UI support for create address vs. use existing address

### ISSUE THREAD

**Issue by WillBreezy** [hclivess/Bismuth#206]
Users that wish to check the balance in their wallet while keys are missing (e.g.: in cold storage), or users that forget to restore their keys before launching the wallet, end up generating a new address upon launch.

Adding support for New vs. Existing address storage, would better support wallet monitoring without key presence. This would also reduce the number of orphaned addresses.

**Proposed implementation:**
- Implement new popup on wallet launch with two options:  "Create New Address" and "Use Existing Address"
- On the main wallet UI, allow the user to tag the current address as the "default address" , which stores the address string in a file for future consumption
- If valid key files are present, the "Create New Address" option is disabled to reduce the chance of a user clobbering their key files accidentally
  - Alternatively, the popup is circumvented and Use Existing Address is activated
- If the default file is present, the "Use Existing Address" option automatically loads the stored default address
- If the default file is not present and no key files are present, the "Use Existing Address" option loads the main UI without generating a new address (leaving the address field blank for the user to manually input their address)
  - Useful (e.g.:) in a situation where a user may be restoring their wallet installation, without intending to initiate a transaction
- If a default file and valid keys are both present, and the addresses within are mismatched, the address in the key file supersedes the default address

**Gap Acknowledgements:**
1. In the above proposal, the user must manually remove valid key files to access "Create New Address"
2. In the above proposal, the user must manually remove the "default address" file to unset the default on their machine
   - These gaps feel acceptable for the proposed incremental improvement

**Comment by jimhsu** [comment]
An implementation that I feel works is skycoin's https://github.com/skycoin/skycoin wallet; there, some metadata is stored along with the key data so that wallets can be handled as multiple single files, users can identify wallets e.g. with a description, and wallets are portable between systems. I would suggest also that keys be moved to either ~/.bismuth/keys or %appdata/Bismuth/keys to respect traditional system conventions.

**Comment by WillBreezy** [comment]
I don't disagree with any of that. Good perspective, thanks!

**Comment by EggPool** [comment]
There is some work from @maccaspacca to handle multiple addresses on one wallet.
This could be integrated with that, extending the functionality to allow "read only" addresses with privkey omitted.
I think the current version relies on a sqlite database for storing keys (so, single file that could be stored in default user directory, good suggestion).
Also, my json-rpc server uses a custom wallet directory and class that could be extended to support read only addresses, but it's no database nor single file (didn't want to risk corrupt data)

**Comment by hclivess** [comment]
Taken into consideration, althought you need to receive coins to be visible on the chain, so new addresses add 0 bloat
