### ISSUE TITLE
[Tokens] Feature request and Ideas

### ISSUE THREAD

**Issue by EggPool** [hclivess/Bismuth#207]
Labels for tokens are missing (issuing, transfer) as well as doc
https://cryptobismuth.slack.com/files/U5VGAVDJB/F9DHCASRH/tokendata.png

**Comment by EggPool** [comment]
Unrelated: we can imagine some kind of extensions to the message formalism.
For instance, the issuer of the token could send a message to self, with a specific message and some b64 encoded icon to be used. Then the wallets/apps will be aware and could use.
message and icon format have to be defined.
Other extensions to the token messages could be specified.

**Comment by hclivess** [comment]
Indeed, we already used encoded icons before

**Comment by hclivess** [comment]
added labels to GUI

**Comment by hclivess** [comment]
Not to be added to legacy wallet with most probability, can be wallet-based, interpretative
