### ISSUE TITLE
[Wallet] UI not completely visible at certain resolutions

### ISSUE THREAD

**Issue by wellspokenman** [hclivess/Bismuth#208]
The Encrypted, Unlock and Lock buttons at the bottom of the wallet UI are not visible at 1600x900 using Win10x64, and the interface cannot be resized or moved in a way to make those buttons visible.

**Comment by hclivess** [comment]
Hello, if you are using a virtual machine, you need to add more virtual memory

**Comment by wellspokenman** [comment]
[Here](https://imgur.com/a/tUuvq)'s an example from an even lower res: 1366*768 - the buttons are only visible if I hide the taskbar. No scrollbar appears when the UI is not sized properly, nor are the buttons positioned within the visible area.

**Comment by hclivess** [comment]
Unfortunately, tkinter does not offer much to remedy this on certain configurations
An HTML wallet is under development

**Comment by wellspokenman** [comment]
Oh well, we should close the issue then. Thanks for a prompt response.

**Comment by hclivess** [comment]
Hello, in new releases, you will be able to fully configure the wallet size with gui_scaling in config.txt

**Comment by wellspokenman** [comment]
awesome - thank you
