### ISSUE TITLE
Simplier regexp

### ISSUE THREAD

**Issue by EggPool** [hclivess/Bismuth#211]
https://github.com/hclivess/Bismuth/blob/0a47a1d03c1f67c97f105d4c520fbab6362e630e/node.py#L2129

`if len(address_validate) == 56 and not re.search("[^abcdef0123456789]", address_validate):`

can be much simpler and avoid double negation:
`if re.match('[abcdef0123456789]{56}', address_validate):`
takes care of all

**Comment by hclivess** [comment]
adopted
