### ISSUE TITLE
Extra checks on transaction?

### ISSUE THREAD

**Issue by EggPool** [hclivess/Bismuth#216]
https://github.com/hclivess/Bismuth/blob/6a9a27413599689cefbd0f1c4c5cfb89501bb0fb/node.py#L912
Mainly affects miners:
Transactions are checked when received, notably for existing balance.
But a rollback can occur just later on, and lead to an insufficient balance (miner reward gone or inbound transaction gone)

Then a tx in mempool can be no more valid.
If a miner embeds it into a block, this block would be rejected by the nodes, then the miner is stuck until the mempool clears.

When rollbacking, it would be nice to re-validate the transaction for balance before re-injecting.

Also, some periodical re-validation of the mempool transactions could be done if there were rollbacks, to mitigate part of the issue.
Has to be dealt with care, since balance checking is not an innocuous operation for the db load

**Comment by hclivess** [comment]
You are right, we should use mempool_merge()

**Comment by hclivess** [comment]
should be patched, live-testing
