### ISSUE TITLE
Boolean wanted

### ISSUE THREAD

**Issue by EggPool** [hclivess/Bismuth#218]
https://github.com/hclivess/Bismuth/blob/6a9a27413599689cefbd0f1c4c5cfb89501bb0fb/node.py#L111

This is very error prone and uses unneeded memory.
Rather use a boolean and change the function name to avoid any doubt on the meaning of the boolean answer.
Seems pedantic, but it's a sure way to have future bugs.

**Comment by hclivess** [comment]
agreed

**Comment by hclivess** [comment]
same for banned, etc

**Comment by hclivess** [comment]
https://github.com/hclivess/Bismuth/commit/05ea7122d99138323ea89a0a1a67ca1031638315
