### ISSUE TITLE
Wasted time

### ISSUE THREAD

**Issue by EggPool** [hclivess/Bismuth#219]
https://github.com/hclivess/Bismuth/blob/2ac42ebc57680109215fdc0a9b3c9f7b0a23fe50/node.py#L428
Whole rows are returned then parsed one by one to extract only 2 columns, then append many dups,  then dedup.
sql can do this in one operation, using less time and memory

"SELECT distinct(recipient) FROM transactions WHERE (block_height < ?) ORDER BY block_height;"
will return only the same set of distinct addresses as the previous query and python loop.
(Only the genesis address may be missing)
no need for a loop, a fetchall() with that query will do

**Comment by hclivess** [comment]
I have a suspicion that fetchall returns all the results to memory, while "for row in" goes by single rows. I have recently had RAM issues with fetchall on this one. What do you think?

**Comment by hclivess** [comment]
But you are right, this particular part is unoptimized, will take a look

**Comment by EggPool** [comment]
yes for fetchall, but there you end up .append() all the adresses (all the rows) in memory anyway, to dedup. so consuming more.
select * and fetchall would fetch all the data, that's not good. 
but here, the select distinct() and fetchall only retrieve the dedup list, as a whole, and that's just what we want in the end, nothing wasted

**Comment by hclivess** [comment]
fixed in https://github.com/hclivess/Bismuth/commit/05ea7122d99138323ea89a0a1a67ca1031638315
added some try/except for those functions too for more security
