### ISSUE TITLE
Reduce requests and code

### ISSUE THREAD

**Issue by EggPool** [hclivess/Bismuth#220]
https://github.com/hclivess/Bismuth/blob/2ac42ebc57680109215fdc0a9b3c9f7b0a23fe50/node.py#L438

Since we only need the balance, we can go with only 2 requests and simpler code:

hyp.execute("SELECT sum(amount)+sum(reward) FROM transactions WHERE (recipient = ? AND block_height < ?);", (x, int(db_block_height) - depth) )
credit = hyp.fetchone()[0]
credit = 0 if credit is None

then the debits :
hyp.execute("SELECT sum(amount)+sum(fee) FROM transactions WHERE (address = ? AND block_height < ?);", (x, int(db_block_height) - depth) )
debit = hyp.fetchone()[0]
debit = 0 if debit is None

and balance is credit - debit

also, float('%.8f' % debit) does not help precision issue, better let debit alone

**Comment by hclivess** [comment]
Thank you, good improvement, adding now

**Comment by hclivess** [comment]
https://github.com/hclivess/Bismuth/commit/05ea7122d99138323ea89a0a1a67ca1031638315
