### ISSUE TITLE
[Feature Request] walletnotify config argument

### ISSUE THREAD

**Issue by Aareon** [hclivess/Bismuth#223]
Reference: https://en.bitcoin.it/wiki/Running_Bitcoin

A wallet transaction includes any transaction for any given address belonging to said wallet.

Usage: `-walletnotify=echo “Transaction received... TXID: %s”`

**Comment by EggPool** [comment]
Moving to https://github.com/EggPool/BismuthRPC/issues/17 since this concerns the json-rpc server

**Comment by hclivess** [comment]
moved/closed
