### ISSUE TITLE
genesis.py error generating address

### ISSUE THREAD

**Issue by idrispendisbey** [hclivess/Bismuth#232]
I just cloned Bismuth to my freshly installed Ubuntu 16.04 with the most recent python 3.6 anaconda.

When I entered command `python genesis.py`, code gave the below error but still managed to create address.txt, pubkey.der, privkey.der files. 

Traceback (most recent call last):
  File "genesis.py", line 45, in <module>
    key = RSA.importKey(open('privkey.der').read())
  File "/home/devc/anaconda3/lib/python3.6/site-packages/Crypto/PublicKey/RSA.py", line 682, in importKey
    raise ValueError("RSA key format is not supported")
ValueError: RSA key format is not supported

Following this, when I tried the wallet.py file this error is received:

Traceback (most recent call last):
  File "wallet.py", line 29, in <module>
    key, public_key_readable, private_key_readable, encrypted, unlocked, public_key_hashed, myaddress = essentials.keys_load(private_key_load, public_key_load)
  File "/home/devc/projects/Bismuth/essentials.py", line 77, in keys_load
    raise ValueError("Invalid public key length: {}".format(len(public_key_readable)))
ValueError: Invalid public key length: 815

Can you guide me on how to properly  generate the addresses?

**Comment by EggPool** [comment]
What is your goal running genesis.py?
What do you think that does?

No need to run that.
node.py then wallet.py are the things to run.

Also make sure you use pycryptodome and not pycrypto, since pycrypto can give broken keys.

**Comment by idrispendisbey** [comment]
Oops my mistake. I just wanted to generate a keypair without downloading the node. It runs smoothly after running the node and wallet. Than you for your answer.

**Comment by hclivess** [comment]
genesis tool is a little misleading and outdated, perhaps I should move it to some folder or somewhere
