### ISSUE TITLE
The blockex API is missing a command to turn a txid into transaction info?

### ISSUE THREAD

**Issue by untilted-document** [hclivess/Bismuth#235]
The API page on the block explorer doesn't seem to cite a method I can use to turn a txid into info about the transaction - I can see http://bismuth.online/api/transaction/blocknumber=amount but I don't have block#/amount. I also see api/hash/somehashvalue but I think that takes a block hash.

I can bash a txid into the Ledger Query form, but I'd rather not HTTP POST to that, and parse the results. Can the API do it directly?

**Comment by hclivess** [comment]
Hello, please post this issue to https://github.com/maccaspacca/BismuthToolsWeb
