### ISSUE TITLE
Missing checksum for release files

### ISSUE THREAD

**Issue by titanomachy** [hclivess/Bismuth#239]
There are no checksums for the release files. I like to be sure that the archive I download has not been tampered with. This is a standard security practice and for a blockchain project a must.

Just a suggestion, but I like how Parity is doing this, e.g. https://github.com/paritytech/parity/releases

**Comment by hclivess** [comment]
What is the reason for the checksum? When downloading from some other place than github? I can add signed checksums

**Comment by titanomachy** [comment]
If you could sign the release commits that would be even better. Bitcoin, Ethereum, Monero and ZCash do sign them too. I like to know that the file was transferred correctly and nothing has been added. I am fetching the checksum from multiple locations and checking the signature.

![verified](https://user-images.githubusercontent.com/1170510/39041936-fbc17c0e-4489-11e8-9b14-82604cd8b98d.png)

**Comment by hclivess** [comment]
Thanks for the suggestion, I will look into it in the forseeable future

**Comment by hclivess** [comment]
I believe GitHub or PyCharm enhanced this and is now in place
