### ISSUE TITLE
Create basic documentation for source tree usage

### ISSUE THREAD

**Issue by cryptonoob42** [hclivess/Bismuth#258]
Attempting to clone and run Bismuth on Ubuntu: it's easy for experienced Python people to figure out what needs to be done in order to run the software, BUT: the README is very short and it tells the user nothing about setup requirements. It would be good to have a "Getting started" document. It wouldn't have to be extremely long, but it should cover at least the following topics:

* General requirements: can Bismuth run on Python 2 or does it require Python 3?
* Installing requirements to run the node (i.e. run pip install -r requirements-node.txt etc.)
* Installing requirements to run the wallet (i.e. run pip install -r requirements.txt)
* Running the node
* Running the wallet

If it helps, I can contribute such a description.

**Comment by hclivess** [comment]
Hello, for basic instructions please refer to https://github.com/EggPool/BismuthHowto
I will add the link to readme

**Comment by cryptonoob42** [comment]
Fixed with commit https://github.com/hclivess/Bismuth/commit/2264bf7bc655fbc949712eab566b2f07cd891d55 - thanks!
