### ISSUE TITLE
Release 4.2.4.5: requirement for PIL.ImageTk not documented

### ISSUE THREAD

**Issue by cryptonoob42** [hclivess/Bismuth#259]
I downloaded the 4.2.4.5 source tar.gz, installed requirements via pip, and got the following:

    foo@bar ~/Downloads/Bismuth-4.2.4.5 $ python3 wallet.py
    Traceback (most recent call last):
    File "wallet.py", line 6, in <module>
      import PIL.Image, PIL.ImageTk, pyqrcode, os, hashlib, time, base64, connections, icons, log, socks, ast, options, tarfile, glob, essentials, re, platform
    ImportError: No module named 'PIL.ImageTk'

The requirements.txt looks like this:

    foo@bar ~/Downloads/Bismuth-4.2.4.5 $ cat requirements.txt 
    # Pip3 requirements for a node and wallet setup
    
    # You need to manually run the following line first
    # pip3 install simple-crypt --no-deps
    
    # Now the minimal modules needed for a full install
    
    PySocks
    pycryptodome
    pillow
    pyqrcode
    matplotlib
    
    # request may be needed by helper scripts
    requests
    
    # These are no more used
    # pypng
    # pyinstaller

/usr/lib/python3/dist-packages/PIL does NOT contain ImageTk.py. One way of fixing this (on Ubuntu) is to run

``
sudo apt install python3-pil.imagetk
``

Afterwards, it's possible to start the wallet. This requirement should be documented somewhere.

**Comment by cryptonoob42** [comment]
I don't know whether it's actually possible to install PIL.ImageTk via pip, so I changed the issue subject to better match the problem description.

**Comment by hclivess** [comment]
Hello, isn't Pillow a drop-in replacement for PIL? Do you have that one installed?

**Comment by cryptonoob42** [comment]
I did pip3 install -r requirements.txt again. Content of requirements.txt unchanged, see above. Output:

	Requirement already satisfied: PySocks in /usr/lib/python3/dist-packages (from -r requirements.txt (line 8)) (1.5.0)
	Requirement already satisfied: pycryptodome in /usr/local/lib/python3.5/dist-packages (from -r requirements.txt (line 9)) (3.6.1)
	Requirement already satisfied: pillow in /usr/lib/python3/dist-packages (from -r requirements.txt (line 10)) (3.1.2)
	Requirement already satisfied: pyqrcode in /usr/local/lib/python3.5/dist-packages (from -r requirements.txt (line 11)) (1.2.1)
	Requirement already satisfied: matplotlib in /usr/local/lib/python3.5/dist-packages (from -r requirements.txt (line 12)) (2.2.2)
	Requirement already satisfied: requests in /usr/lib/python3/dist-packages (from -r requirements.txt (line 15)) (2.9.1)
	Requirement already satisfied: kiwisolver>=1.0.1 in /usr/local/lib/python3.5/dist-packages (from matplotlib->-r requirements.txt (line 12)) (1.0.1)
	Requirement already satisfied: pytz in /usr/local/lib/python3.5/dist-packages (from matplotlib->-r requirements.txt (line 12)) (2018.4)
	Requirement already satisfied: six>=1.10 in /usr/lib/python3/dist-packages (from matplotlib->-r requirements.txt (line 12)) (1.10.0)
	Requirement already satisfied: numpy>=1.7.1 in /usr/local/lib/python3.5/dist-packages (from matplotlib->-r requirements.txt (line 12)) (1.14.3)
	Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.5/dist-packages (from matplotlib->-r requirements.txt (line 12)) (0.10.0)
	Requirement already satisfied: pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.1 in /usr/local/lib/python3.5/dist-packages (from matplotlib->-r requirements.txt (line 12)) (2.2.0)
	Requirement already satisfied: python-dateutil>=2.1 in /usr/local/lib/python3.5/dist-packages (from matplotlib->-r requirements.txt (line 12)) (2.7.3)
	Requirement already satisfied: setuptools in /usr/local/lib/python3.5/dist-packages (from kiwisolver>=1.0.1->matplotlib->-r requirements.txt (line 12)) (39.0.1)

It seems that the problem on my system is that Pillow 3.1.2 is already installed, but 3.1.2 does NOT provide a module named ImageTk. This appears to have been introduced in later versions of Pillow. As the requirements.txt does not specify a version, pip sees that Pillow is already installed and assumes that the requirement is satisfied. A fix for this problem would probably be to specify the minimum required version of Pillow in requirements.txt.

**Comment by cryptonoob42** [comment]
As an addition: I've upgraded Pillow to 5.1.0 and the wallet starts now without installing python3-pil.imagetk via apt.
