### ISSUE TITLE
Wallet: check keys coherence at launch

### ISSUE THREAD

**Issue by EggPool** [hclivess/Bismuth#272]
Wallet should check for key coherence at startup.

- pubkey has to match privkey
- address has to match pubkey

If not, 

- alert the user and no not run the wallet at all
- ask if the wallet should try an auto-fix of the wallet file

**Comment by hclivess** [comment]
There already was a check, but I removed it after adding wallet.der stuff
I'll add a new one. Then in the future, after everyone is using the new wallet, I can swap that conversion procedure to auto recovery

**Comment by hclivess** [comment]
the new wallet design should prevent any mismatches, do you still want the coherence check?

**Comment by hclivess** [comment]
Handled by wallets, overcome issue
