### ISSUE TITLE
wallet.der should be placed in a data directory

### ISSUE THREAD

**Issue by cryptonoob42** [hclivess/Bismuth#275]
The wallet file is currently put into the same directory as wallet.py or wallet.exe. This implies that the wallet file will reside (for example) in

    C:\Program Files (x86)\Bismuth

This is probably also the reason the Windows wallet requires admin privileges, because otherwise it wouldn't be able to place a file in that directory. (see #269)

It would be better to place data files into a data directory, either in the user's home directory or in %APPDATA% etc. on Windows. This would ease upgrades and it would eliminate the risk of the wallet file getting deleted upon deinstallation of the wallet.

**Comment by hclivess** [comment]
ISS does not delete files it has not created upon uninstalling. Also, I am sure this would do nothing in terms of admin privileges.

**Comment by Aareon** [comment]
I don't think this has anything to do with your elevation issues, either. However, as I mentioned in https://github.com/hclivess/Bismuth/issues/293 I would like to eventually move the wallet, ledger, and other applicable files into `.appdata` or equivalent.

**Comment by cryptonoob42** [comment]
I'll take the bet that elevated privileges are no longer required if your idea is implemented @Aareon :)

**Comment by hclivess** [comment]
Many other files are accessed, not just the wallet - logs, modules, peerlists. The elevation is required at startup, at that time, there is no accessing of the wallet.

**Comment by hclivess** [comment]
Why don't you try move everything into user data folder and see if it requires privileges or not?

**Comment by hclivess** [comment]
Hi, did you perform the test?

**Comment by Aareon** [comment]
I've done my own tests, and moving to `AppData`, or even the user path doesn't require elevated privileges.

I know for a fact that if the ownership of the `Program Files` folders (`x86` included) is set to administrators and not the user, Bismuth requires elevation to take temporary ownership. Storing things such as peers, configs, databases (really anything that gets changed). As far as I'm aware, you don't need any special permissions to read files created by Bismuth that are owned by admin.

**Comment by hclivess** [comment]
This file format is outdated, Tornado wallet uses proper storage
