### ISSUE TITLE
Transactions fees

### ISSUE THREAD

**Issue by Pastize** [hclivess/Bismuth#287]
I am unsure how transactions fees work.  I sent .25 from one wallet to another and it said there would be around a .02 fee, yet instead there was around a 1.2 fee.  Can someone explain how transaction fees work?  thanks?

**Comment by hclivess** [comment]
Which interface did you use for sending? The wallet?

**Comment by Pastize** [comment]
Yes, it was through the default wallet app installed from bismuth package installer.

**Comment by hclivess** [comment]
I can check it, but the fees are static and this has already been reviewed
