### ISSUE TITLE
GUI memory leak

### ISSUE THREAD

**Issue by hclivess** [hclivess/Bismuth#3]
Right now, Bismuth GUI is not updating visible elements using the configure method. Instead, it redraws the elements on top of the old ones. This will need to be fixed once automatic GUI refreshing is implemented. For now, it does not pose a threat.

**Comment by hclivess** [comment]
Fixed using update functions, except for the table. Memory appears stable.

**Comment by hclivess** [comment]
Still unstable over a longer periods of time

**Comment by hclivess** [comment]
Tried everything including complete destruction of the f4 frame without any positive results.

**Comment by LamaGanja** [comment]
did you try?

import sched, time
s = sched.scheduler(time.time, time.sleep)
....
def refresh()
....
#buttons
s.enter(60,1, refresh)
s.run()

**Comment by hclivess** [comment]
Can you please elaborate and explain the root cause?

**Comment by hclivess** [comment]
fixed with 

        for child in f4.winfo_children(): #prevent hangup
            child.destroy()

and manual refresh function separation

root cause: table redraw + refresh trigger stack
