### ISSUE TITLE
Is there any macbook wallet ?

### ISSUE THREAD

**Issue by coinheo** [hclivess/Bismuth#354]
i couldnt find bismuth wallet for mac, can anyone help me about this ?

**Comment by EggPool** [comment]
The light wallet is pure python, runs from source on Mac, see 
https://github.com/bismuthfoundation/Bismuth-FAQ/blob/master/Install/macOS.md

Head over to the discord for help: https://discord.gg/cmHzDgR

**Comment by hclivess** [comment]
Does https://github.com/bismuthfoundation/WalletServer work?

**Comment by EggPool** [comment]
> Does https://github.com/bismuthfoundation/WalletServer work?

This is the wallet server.

The most recent wallet client is
https://github.com/bismuthfoundation/TornadoWallet/releases

And comes with Mac Os package.

**Comment by hclivess** [comment]
Thanks and thanks
