### ISSUE TITLE
Exception with empty database

### ISSUE THREAD

**Issue by icook** [hclivess/Bismuth#356]
Line https://github.com/hclivess/Bismuth/blob/master/node.py#L1342 explodes if the for loop above it never runs, because `y = None` and `None - 1000` raises a `TypeError`. Not sure what the right fix here is but I just patched it to read `str(y or 0 - 1000)`.

**Comment by hclivess** [comment]
Hello, this is an anchor block for testing if the database is OK on start. I'd say 

`
if y:
        with open("coherence_last", 'w') as filename:
            filename.write(str(y - 1000))  # room for rollbacks
`

**Comment by icook** [comment]
Seems reasonable, thanks.
