### ISSUE TITLE
Node API Call | diffgetjson returns incorrect information

### ISSUE THREAD

**Issue by maccaspacca** [hclivess/Bismuth#365]
Current code (from line 1728)

elif data == "diffgetjson":
	if node.peers.is_allowed(peer_ip, data):
		diff = node.difficulty
		response = {"difficulty": diff[0],
					"diff_dropped": diff[0],
					"time_to_generate": diff[0],
					"diff_block_previous": diff[0],
					"block_time": diff[0],
					"hashrate": diff[0],
					"diff_adjustment": diff[0],
					"block_height": diff[0]}

Should be:

elif data == "diffgetjson":
	if node.peers.is_allowed(peer_ip, data):
		diff = node.difficulty
		response = {"difficulty": diff[0],
					"diff_dropped": diff[1],
					"time_to_generate": diff[2],
					"diff_block_previous": diff[3],
					"block_time": diff[4],
					"hashrate": diff[5],
					"diff_adjustment": diff[6],
					"block_height": diff[7]}

**Comment by maccaspacca** [comment]
I see this is fixed. Thanks Hclivess

**Comment by hclivess** [comment]
I forgot to let you know, was probably in a hurry, sorry
