### ISSUE TITLE
Wrong interface

### ISSUE THREAD

**Issue by EggPool** [hclivess/Bismuth#371]
https://github.com/hclivess/Bismuth/blob/0e705795f2e161d423f1f45cb1505dffbeeb5b82/node.py#L426

Mempool object should be used in a storage agnostic way, with no outside sql requests.
It could evolve into something not sql at all.

So SQL requests are defined within mempool module, and this call would be a generic
mp.MEMPOOL.get_balance(address)

mempool object only needs the address to check, and sends back an amount.
nothing else has to surface to the outside world, hos it's done is the mempool module sole responsability.

**Comment by hclivess** [comment]
Is this a request to move queries to functions to have them separated to be able to redirect by simply changing a module? I agree to this, would you like me to start implementing it?

**Comment by EggPool** [comment]
Let say it's a reminder of how the mempool module was architectured, and what are the goals of such OOP design:
The mempool object is supposed to abstract all low level operations in the module itself, via private properties/methods, so the dev should never worry about how it's done, low level.
Only the public interface is used to deal with the mempool.

Mempool, what is your transaction list?
I don't need to know where to look for, if this is a flat file or sqlite or anything, I want a list of transactions from one call with no param.
When I'm dealing with the node flow, the details are just in the way, I don't need to see them, I want them buried under the responsibility of the module.

Mempool, what is balance of mempool tx for address AA ?
I just need to provide an address, the mempool deal with the rest. 
No extra param, no knowledge of the inner workings.

This allow to have clear responsibilities: the node which uses the mempool module just has to ask high level questions, and does not need to know how it works or what specific params the mempool needs.
Just use a generic and explicit interface, which can be stable even if the storage engine should change.
That will lighten the node code a lot, and make it more explicit. What we ask the mempool is clear.

Anything can change in the mempool module provided the interface does not change.
MEMPOOL, a global instance of Mempool, should be the only global variable from the module ever used from the outside.

Also eases a lot testing, since then the module can be stress tested at will.

This goes beyond the current state, since when I made that module, I didn't want to change the node code too much, so it stills sends a cursor back sometimes.
Ideally, It should not, but send a list of transactions back.
Transactions being also core objects, not a list in that context, a dict in that one, aso...

That spirit applies to other parts of the code, too. Mempool is a good example in the right direction.
Many place, we have low level parameters being fed again and again in functions or modules that shouldn't need them (or just once at init) if they were properly considered as objects.

**Comment by hclivess** [comment]
Agreed, this is a good recapitulation of the direction we agreed on.
