### ISSUE TITLE
Uncovered code in master

### ISSUE THREAD

**Issue by Aareon** [hclivess/Bismuth#372]
https://github.com/hclivess/Bismuth/blob/5c3c2f23c1b81763e3f6240be40d8d1e0ea86fb5/node.py#L814

As far as I can see, all instances where `received_block_height` is referenced are uncovered code as the definition cannot be found anywhere in the code base. Please correct me if I'm wrong.

**Edit: I could be wrong, because there *is* a definition in `worker.py`, but there is a reference to `received_block_height` in `node.py` without an import. Could be dead code.**

**Comment by hclivess** [comment]
Good catch. The thing is that the protocol does not allow `blocksfnd` message before  `blockheight` message, which defines it. But it should be an object property (probably Client class) with some initialization

**Comment by Aareon** [comment]
Or as a property for the peer class, as that would be a variable defined per whichever peer is responding.

**Comment by hclivess** [comment]
Maybe, but since it is in the `classes.Client()` thread and threads could have different data, I would prefer to keep it there. Refactoring is always a possibility.

**Comment by Aareon** [comment]
I've been considering moving the `Node` class out of `classes`, personally. I think it would make more sense to have those classes in their appropriate files. That way all of the logic for a specific portion of the program is in an appropriate place, ultimately phasing out the need for the `classes` file altogether.

**Comment by hclivess** [comment]
Acceptable, classes.py is just a central reference, it does not really need to exist

**Comment by EggPool** [comment]
Agreed. 
Python way is to have 
"Class" in a class.py file and its instance named "class" (case sensitive)
Moving libs in a module directory to help sorting out scripts (things to be run) vs class/helpers (imported code) would also help a lot.
No need for 36 levels, just some basic structure to make things more clear for an occasional dev giving a look.

**Comment by Aareon** [comment]
I know it would help myself a lot 😊

**Comment by hclivess** [comment]
addressed in new repository
