### ISSUE TITLE
Rewards calculation in node api commands balanceget and balancegetjson

### ISSUE THREAD

**Issue by maccaspacca** [hclivess/Bismuth#373]
When using api commands "balanceget" or "balancegetjson" - rewards returns "0" and the balance calculation does not include rewards for addresses that have mined blocks.

**Comment by maccaspacca** [comment]
The error is in line 417 in node.py
 entries = db_handler.c.fetchall()

Should be:
 entries = db_handler.h3.fetchall()

**Comment by maccaspacca** [comment]
With this fix an address that has never mined a block returns a list of zeros reulting in "0E-8" for str(rewards).
Perhaps something like putting an extra line below line 424:
rewards = 0 if str(rewards) == "0E-8" else rewards

or maybe changing the initial sql query to "SELECT sum(reward) FROM transactions WHERE recipient = ?;" and then returning the quantize_eight result as a string would simplify it all a little bit?

**Comment by hclivess** [comment]
Hi, I'm discontinuing h3 to streamline the code
I'm putting in `entries = db_handler.h.fetchall()`
There was a discrepancy anyway, thanks for noticing
I'll merge the /dev to /master now

**Comment by maccaspacca** [comment]
That's great 👍
