### ISSUE TITLE
Extreme Blockchain Compression

### ISSUE THREAD

**Issue by hclivess** [hclivess/Bismuth#7]
This block chain can be compressed using references to data which already exist and are static ( sender address, recipient address, public key). The procedure would simply require the node to search these data in a certain block, if it receives a substitute in form of a number (5 -> go search public key/address in block height 5). 

This compression method will also enable decentralized applications to be re-deployed.

**Comment by hclivess** [comment]
https://bitcointalk.org/index.php?topic=1525078.msg17128246#msg17128246

**Comment by HarryR** [comment]
This will take less storage on disk and network transfer, but would require each node to do *many many* disk seeks to read the DB to uncompress the data into a verifiable format.

**Comment by hclivess** [comment]
Yes, and is currently not compatible with hyperblocks

**Comment by hclivess** [comment]
Discontinued for now
