### ISSUE TITLE
Low database performance, skip balance check on mining blocks

### ISSUE THREAD

**Issue by hclivess** [hclivess/Bismuth#70]
Move retargeting of difficulty at least to 100 blocks

**Comment by hclivess** [comment]
Test proves no real impact on performance, seek other ways

**Comment by hclivess** [comment]
todo: skip balance check on mining blocks instead

**Comment by HarryR** [comment]
Stop re-opening and closing the database all the time...?

**Comment by hclivess** [comment]
Yes, the code consists of formerly small pieces that were added and removed over time, need to find some larger ranges for the open database now before closing sessions.

**Comment by hclivess** [comment]
DB changes to single session, also RAM will be available
