### ISSUE TITLE
Mine blocks, but reward another account

### ISSUE THREAD

**Issue by HarryR** [hclivess/Bismuth#77]
When a block is mined the address for the transaction is also the recipient. Like "I create new money for myself, see here is my special token that makes everything OK'. The public key included in the transaction is that of the `address`, and the transaction is signed with that key.

But... that means if I'm mining blocks then the miner's wallet is 'Online' - e.g. the private key material which holds the funds is stored on the same server as the miner.

Ideally, for safety, simplicity and security, it would be good to be able to mine a transaction and have the reward paid out to another account which is 'Offline' and safely separated from the miner.

Looking at the code I can't immediately see anything that would prevent this, but would be good to get a second opinion.

**Comment by hclivess** [comment]
Thanks, I'll look into this

**Comment by hclivess** [comment]
If you put miner into a different folder with a different set of keys, it will not send the private key to the node or use the node's private key, especially now when all the data is remotely pulled from the distant node with "hashlast" and "diffget" commands and the miner is no longer required to have a node running on the same machine. This also opens doors for light clients which I will focus on soon.

**Comment by HarryR** [comment]
I'm thinking specifically about delegated mining, where neither miners nor the pool have the private keys for the accounts their mining for, this is absolutely critical for my use case and absolutely critical for security.

This means you can put the miner on machines, and if any one of them gets compromised the existing balance of your account is untouchable.

**Comment by hclivess** [comment]
Miner.py takes an optional "address" argument , if you supply it, the miner will submit blocks with an arbitrary address for payout, but signed with it's own signature. Have you tested this feature?

**Comment by aayanl** [comment]
To add on to this, it should also be possible to pay to multiple addresses at once

**Comment by hclivess** [comment]
There is no reason to split the transaction, you would not save anything in terms of network bandwidth. I do not support the "sendmany" approach, at least as of now. Fees are in place to prevent spam and "sendmany" goes against that.
