### ISSUE TITLE
Consider an alternative to 1024bit RSA

### ISSUE THREAD

**Issue by HarryR** [hclivess/Bismuth#78]
While 1024bit RSA is generally considered deprecated, in reality it's still relatively safe given that the largest known factorisation has been RSA-768 in late 2009.

However, it would be worth investigating X25519 and Ed25519 (via NaCl, libsodium, TweetNaCl etc.) as they are significantly faster than RSA, and in most use-cases will eliminate the need to store the public key in the transaction log as the `address` and `recipient` fields don't need to be hashes of the public key (as with RSA) - they can be the public keys themselves encoded with Base32, other bases would be even smaller.

e.g. a base32 encoded Ed25519 public key is: `urmhlcidm5kq5yiejnivyuxrpxbvkcrsyg3x5ppuometldhq6lp` (51 bytes)

The downside is that this would be incompatible with... everything

**Comment by aayanl** [comment]
4096 is the standard now and should be enough for a long long while. Takes no time at all to generate a 4096 key with my phone

**Comment by hclivess** [comment]
Hm, it could be compatible with the current system, testing will be done 

    key = RSA.generate(1024, random_generator)

**Comment by hclivess** [comment]
I have added support for 4096 keys now, X25519 or Ed25519 is a great idea, thanks, perhaps for some major upgrade
