### ISSUE TITLE
127.0.0.1 Banned

### ISSUE THREAD

**Issue by Stoner19** [hclivess/Bismuth#80]
When running the miner I get `2017-05-26 09:41:10,274 handle(1077) IP 127.0.0.1 banned, disconnected`

I've tried a fresh clone of the repo and that doesn't seem to matter.

**Comment by hclivess** [comment]
Enable extended logging and see what happens on the node's side (or in node.log)

**Comment by hclivess** [comment]
There was a sync problem for nodes with non-forwarded ports, which might have caused this. Please try the new version.

**Comment by Stoner19** [comment]
pretty sure this has been fixed. Will close for now.
