### ISSUE TITLE
Create delayed transactions with sums (LN 2.0)

### ISSUE THREAD

**Issue by hclivess** [hclivess/Bismuth#94]
Adapt anon mixer to process offchain transactions

**Comment by hclivess** [comment]
Not sure what I meant, perhaps something DAO-related, with funds locked in a channel?

**Comment by hclivess** [comment]
let users exchange messages about how much they are sending to each other, then have a multi-signature process where both confirm (or cancel)

**Comment by EggPool** [comment]
May be related to atomic swap mechanism
https://github.com/EggPool/BismuthRPC/issues/9
